2018-05-17 07:40:59.096 [error] <0.16886.0> Connection Id 53580 closing with reason: tcp_closed
2018-05-17 07:40:59.096 [error] <0.16886.0> gen_server <0.16886.0> terminated with reason: tcp_closed
2018-05-17 07:40:59.096 [error] <0.16886.0> CRASH REPORT Process <0.16886.0> with 0 neighbours exited with reason: tcp_closed in gen_server:handle_common_reply/8 line 726
2018-05-17 07:40:59.097 [error] <0.145.0> Supervisor {<0.145.0>,poolboy_sup} had child mysql started with {mysql,start_link,undefined} at <0.16886.0> exit with reason tcp_closed in context child_terminated
2018-05-17 07:40:59.100 [error] <0.16887.0> Connection Id 53581 closing with reason: tcp_closed
2018-05-17 07:40:59.100 [error] <0.16887.0> gen_server <0.16887.0> terminated with reason: tcp_closed
2018-05-17 07:40:59.100 [error] <0.16887.0> CRASH REPORT Process <0.16887.0> with 0 neighbours exited with reason: tcp_closed in gen_server:handle_common_reply/8 line 726
2018-05-17 07:40:59.103 [error] <0.145.0> Supervisor {<0.145.0>,poolboy_sup} had child mysql started with {mysql,start_link,undefined} at <0.16887.0> exit with reason tcp_closed in context child_terminated
2018-05-17 07:41:20.090 [error] <0.16888.0> Connection Id 53582 closing with reason: tcp_closed
2018-05-17 07:41:20.090 [error] <0.16888.0> gen_server <0.16888.0> terminated with reason: tcp_closed
2018-05-17 07:41:20.090 [error] <0.16888.0> CRASH REPORT Process <0.16888.0> with 0 neighbours exited with reason: tcp_closed in gen_server:handle_common_reply/8 line 726
2018-05-17 07:41:20.091 [error] <0.145.0> Supervisor {<0.145.0>,poolboy_sup} had child mysql started with {mysql,start_link,undefined} at <0.16888.0> exit with reason tcp_closed in context child_terminated
2018-05-17 07:41:20.095 [error] <0.16889.0> Connection Id 53583 closing with reason: tcp_closed
2018-05-17 07:41:20.095 [error] <0.16889.0> gen_server <0.16889.0> terminated with reason: tcp_closed
2018-05-17 07:41:20.095 [error] <0.16889.0> CRASH REPORT Process <0.16889.0> with 0 neighbours exited with reason: tcp_closed in gen_server:handle_common_reply/8 line 726
2018-05-17 07:41:20.097 [error] <0.145.0> Supervisor {<0.145.0>,poolboy_sup} had child mysql started with {mysql,start_link,undefined} at <0.16889.0> exit with reason tcp_closed in context child_terminated
2018-05-17 07:41:41.090 [error] <0.16893.0> Connection Id 53584 closing with reason: tcp_closed
2018-05-17 07:41:41.090 [error] <0.16893.0> gen_server <0.16893.0> terminated with reason: tcp_closed
2018-05-17 07:41:41.090 [error] <0.16893.0> CRASH REPORT Process <0.16893.0> with 0 neighbours exited with reason: tcp_closed in gen_server:handle_common_reply/8 line 726
2018-05-17 07:41:41.090 [error] <0.145.0> Supervisor {<0.145.0>,poolboy_sup} had child mysql started with {mysql,start_link,undefined} at <0.16893.0> exit with reason tcp_closed in context child_terminated
2018-05-17 07:41:41.110 [error] <0.16894.0> Connection Id 53585 closing with reason: tcp_closed
2018-05-17 07:41:41.110 [error] <0.16894.0> gen_server <0.16894.0> terminated with reason: tcp_closed
2018-05-17 07:41:41.110 [error] <0.16894.0> CRASH REPORT Process <0.16894.0> with 0 neighbours exited with reason: tcp_closed in gen_server:handle_common_reply/8 line 726
2018-05-17 07:41:41.111 [error] <0.145.0> Supervisor {<0.145.0>,poolboy_sup} had child mysql started with {mysql,start_link,undefined} at <0.16894.0> exit with reason tcp_closed in context child_terminated
2018-05-17 07:42:02.098 [error] <0.16895.0> Connection Id 53586 closing with reason: tcp_closed
2018-05-17 07:42:02.098 [error] <0.16895.0> gen_server <0.16895.0> terminated with reason: tcp_closed
2018-05-17 07:42:02.098 [error] <0.16895.0> CRASH REPORT Process <0.16895.0> with 0 neighbours exited with reason: tcp_closed in gen_server:handle_common_reply/8 line 726
2018-05-17 07:42:02.098 [error] <0.145.0> Supervisor {<0.145.0>,poolboy_sup} had child mysql started with {mysql,start_link,undefined} at <0.16895.0> exit with reason tcp_closed in context child_terminated
2018-05-17 07:42:02.102 [error] <0.16896.0> Connection Id 53587 closing with reason: tcp_closed
2018-05-17 07:42:02.102 [error] <0.16896.0> gen_server <0.16896.0> terminated with reason: tcp_closed
2018-05-17 07:42:02.102 [error] <0.16896.0> CRASH REPORT Process <0.16896.0> with 0 neighbours exited with reason: tcp_closed in gen_server:handle_common_reply/8 line 726
2018-05-17 07:42:02.104 [error] <0.145.0> Supervisor {<0.145.0>,poolboy_sup} had child mysql started with {mysql,start_link,undefined} at <0.16896.0> exit with reason tcp_closed in context child_terminated
2018-05-17 07:42:23.090 [error] <0.16897.0> Connection Id 53588 closing with reason: tcp_closed
2018-05-17 07:42:23.090 [error] <0.16897.0> gen_server <0.16897.0> terminated with reason: tcp_closed
2018-05-17 07:42:23.090 [error] <0.16897.0> CRASH REPORT Process <0.16897.0> with 0 neighbours exited with reason: tcp_closed in gen_server:handle_common_reply/8 line 726
2018-05-17 07:42:23.090 [error] <0.145.0> Supervisor {<0.145.0>,poolboy_sup} had child mysql started with {mysql,start_link,undefined} at <0.16897.0> exit with reason tcp_closed in context child_terminated
2018-05-17 07:42:23.100 [error] <0.16898.0> Connection Id 53589 closing with reason: tcp_closed
2018-05-17 07:42:23.100 [error] <0.16898.0> gen_server <0.16898.0> terminated with reason: tcp_closed
2018-05-17 07:42:23.100 [error] <0.16898.0> CRASH REPORT Process <0.16898.0> with 0 neighbours exited with reason: tcp_closed in gen_server:handle_common_reply/8 line 726
2018-05-17 07:42:23.101 [error] <0.145.0> Supervisor {<0.145.0>,poolboy_sup} had child mysql started with {mysql,start_link,undefined} at <0.16898.0> exit with reason tcp_closed in context child_terminated
2018-05-17 15:41:05.209 [error] <0.18109.0> Connection Id 53655 closing with reason: tcp_closed
2018-05-17 15:41:05.209 [error] <0.18109.0> gen_server <0.18109.0> terminated with reason: tcp_closed
2018-05-17 15:41:05.210 [error] <0.18109.0> CRASH REPORT Process <0.18109.0> with 0 neighbours exited with reason: tcp_closed in gen_server:handle_common_reply/8 line 726
2018-05-17 15:41:05.210 [error] <0.145.0> Supervisor {<0.145.0>,poolboy_sup} had child mysql started with {mysql,start_link,undefined} at <0.18109.0> exit with reason tcp_closed in context child_terminated
2018-05-17 15:41:05.210 [error] <0.18110.0> Connection Id 53656 closing with reason: tcp_closed
2018-05-17 15:41:05.210 [error] <0.18110.0> gen_server <0.18110.0> terminated with reason: tcp_closed
2018-05-17 15:41:05.218 [error] <0.18110.0> CRASH REPORT Process <0.18110.0> with 0 neighbours exited with reason: tcp_closed in gen_server:handle_common_reply/8 line 726
2018-05-17 15:41:05.423 [error] <0.145.0> Supervisor {<0.145.0>,poolboy_sup} had child mysql started with {mysql,start_link,undefined} at <0.18110.0> exit with reason tcp_closed in context child_terminated
2018-05-17 15:41:26.082 [error] <0.18111.0> Connection Id 53657 closing with reason: tcp_closed
2018-05-17 15:41:26.082 [error] <0.18111.0> gen_server <0.18111.0> terminated with reason: tcp_closed
2018-05-17 15:41:26.083 [error] <0.18111.0> CRASH REPORT Process <0.18111.0> with 0 neighbours exited with reason: tcp_closed in gen_server:handle_common_reply/8 line 726
2018-05-17 15:41:26.083 [error] <0.145.0> Supervisor {<0.145.0>,poolboy_sup} had child mysql started with {mysql,start_link,undefined} at <0.18111.0> exit with reason tcp_closed in context child_terminated
2018-05-17 15:41:26.087 [error] <0.18112.0> Connection Id 53658 closing with reason: tcp_closed
2018-05-17 15:41:26.087 [error] <0.18112.0> gen_server <0.18112.0> terminated with reason: tcp_closed
2018-05-17 15:41:26.088 [error] <0.18112.0> CRASH REPORT Process <0.18112.0> with 0 neighbours exited with reason: tcp_closed in gen_server:handle_common_reply/8 line 726
2018-05-17 15:41:26.089 [error] <0.145.0> Supervisor {<0.145.0>,poolboy_sup} had child mysql started with {mysql,start_link,undefined} at <0.18112.0> exit with reason tcp_closed in context child_terminated
2018-05-17 15:41:47.081 [error] <0.18115.0> Connection Id 53659 closing with reason: tcp_closed
2018-05-17 15:41:47.081 [error] <0.18115.0> gen_server <0.18115.0> terminated with reason: tcp_closed
2018-05-17 15:41:47.082 [error] <0.18115.0> CRASH REPORT Process <0.18115.0> with 0 neighbours exited with reason: tcp_closed in gen_server:handle_common_reply/8 line 726
2018-05-17 15:41:47.082 [error] <0.145.0> Supervisor {<0.145.0>,poolboy_sup} had child mysql started with {mysql,start_link,undefined} at <0.18115.0> exit with reason tcp_closed in context child_terminated
2018-05-17 15:41:47.101 [error] <0.18116.0> Connection Id 53660 closing with reason: tcp_closed
2018-05-17 15:41:47.101 [error] <0.18116.0> gen_server <0.18116.0> terminated with reason: tcp_closed
2018-05-17 15:41:47.101 [error] <0.18116.0> CRASH REPORT Process <0.18116.0> with 0 neighbours exited with reason: tcp_closed in gen_server:handle_common_reply/8 line 726
2018-05-17 15:41:47.102 [error] <0.145.0> Supervisor {<0.145.0>,poolboy_sup} had child mysql started with {mysql,start_link,undefined} at <0.18116.0> exit with reason tcp_closed in context child_terminated
2018-05-17 15:42:08.109 [error] <0.18117.0> Connection Id 53661 closing with reason: tcp_closed
2018-05-17 15:42:08.109 [error] <0.18117.0> gen_server <0.18117.0> terminated with reason: tcp_closed
2018-05-17 15:42:08.109 [error] <0.18117.0> CRASH REPORT Process <0.18117.0> with 0 neighbours exited with reason: tcp_closed in gen_server:handle_common_reply/8 line 726
2018-05-17 15:42:08.109 [error] <0.145.0> Supervisor {<0.145.0>,poolboy_sup} had child mysql started with {mysql,start_link,undefined} at <0.18117.0> exit with reason tcp_closed in context child_terminated
2018-05-17 15:42:08.109 [error] <0.18118.0> Connection Id 53662 closing with reason: tcp_closed
2018-05-17 15:42:08.109 [error] <0.18118.0> gen_server <0.18118.0> terminated with reason: tcp_closed
2018-05-17 15:42:08.109 [error] <0.18118.0> CRASH REPORT Process <0.18118.0> with 0 neighbours exited with reason: tcp_closed in gen_server:handle_common_reply/8 line 726
2018-05-17 15:42:08.114 [error] <0.145.0> Supervisor {<0.145.0>,poolboy_sup} had child mysql started with {mysql,start_link,undefined} at <0.18118.0> exit with reason tcp_closed in context child_terminated
2018-05-17 15:42:29.081 [error] <0.18119.0> Connection Id 53663 closing with reason: tcp_closed
2018-05-17 15:42:29.082 [error] <0.18119.0> gen_server <0.18119.0> terminated with reason: tcp_closed
2018-05-17 15:42:29.082 [error] <0.18119.0> CRASH REPORT Process <0.18119.0> with 0 neighbours exited with reason: tcp_closed in gen_server:handle_common_reply/8 line 726
2018-05-17 15:42:29.082 [error] <0.145.0> Supervisor {<0.145.0>,poolboy_sup} had child mysql started with {mysql,start_link,undefined} at <0.18119.0> exit with reason tcp_closed in context child_terminated
2018-05-17 15:42:29.094 [error] <0.18120.0> Connection Id 53664 closing with reason: tcp_closed
2018-05-17 15:42:29.094 [error] <0.18120.0> gen_server <0.18120.0> terminated with reason: tcp_closed
2018-05-17 15:42:29.094 [error] <0.18120.0> CRASH REPORT Process <0.18120.0> with 0 neighbours exited with reason: tcp_closed in gen_server:handle_common_reply/8 line 726
2018-05-17 15:42:29.095 [error] <0.145.0> Supervisor {<0.145.0>,poolboy_sup} had child mysql started with {mysql,start_link,undefined} at <0.18120.0> exit with reason tcp_closed in context child_terminated
2018-05-17 16:02:41.610 [error] <0.147.0>@wxr_sup:init:39 CRASH REPORT Process <0.147.0> with 0 neighbours crashed with reason: no case clause matching undefined in wxr_sup:init/1 line 39
2018-05-17 16:02:41.610 [error] <0.145.0> CRASH REPORT Process <0.145.0> with 0 neighbours exited with reason: {{{case_clause,undefined},[{wxr_sup,init,1,[{file,"src/wxr_sup.erl"},{line,39}]},{supervisor,init,1,[{file,"supervisor.erl"},{line,294}]},{gen_server,init_it,2,[{file,"gen_server.erl"},{line,365}]},{gen_server,init_it,6,[{file,"gen_server.erl"},{line,333}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]},{wxr_app,start,[normal,[]]}} in application_master:init/4 line 134
2018-05-17 16:20:49.474 [error] <0.147.0>@wxr_sup:init:39 CRASH REPORT Process <0.147.0> with 0 neighbours crashed with reason: no case clause matching undefined in wxr_sup:init/1 line 39
2018-05-17 16:20:49.475 [error] <0.145.0> CRASH REPORT Process <0.145.0> with 0 neighbours exited with reason: {{{case_clause,undefined},[{wxr_sup,init,1,[{file,"src/wxr_sup.erl"},{line,39}]},{supervisor,init,1,[{file,"supervisor.erl"},{line,294}]},{gen_server,init_it,2,[{file,"gen_server.erl"},{line,365}]},{gen_server,init_it,6,[{file,"gen_server.erl"},{line,333}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]},{wxr_app,start,[normal,[]]}} in application_master:init/4 line 134
2018-05-17 16:26:50.713 [error] <0.147.0>@wxr_sup:init:39 CRASH REPORT Process <0.147.0> with 0 neighbours crashed with reason: no case clause matching undefined in wxr_sup:init/1 line 39
2018-05-17 16:26:50.728 [error] <0.147.0>@wxr_sup:init:39 CRASH REPORT Process <0.147.0> with 0 neighbours crashed with reason: no case clause matching undefined in wxr_sup:init/1 line 39
2018-05-17 16:26:50.839 [error] <0.147.0>@wxr_sup:init:39 CRASH REPORT Process <0.147.0> with 0 neighbours crashed with reason: no case clause matching undefined in wxr_sup:init/1 line 39
2018-05-17 16:26:50.713 [error] <0.145.0> CRASH REPORT Process <0.145.0> with 0 neighbours exited with reason: {{{case_clause,undefined},[{wxr_sup,init,1,[{file,"src/wxr_sup.erl"},{line,39}]},{supervisor,init,1,[{file,"supervisor.erl"},{line,294}]},{gen_server,init_it,2,[{file,"gen_server.erl"},{line,365}]},{gen_server,init_it,6,[{file,"gen_server.erl"},{line,333}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]},{wxr_app,start,[normal,[]]}} in application_master:init/4 line 134
2018-05-17 16:26:50.729 [error] <0.145.0> CRASH REPORT Process <0.145.0> with 0 neighbours exited with reason: {{{case_clause,undefined},[{wxr_sup,init,1,[{file,"src/wxr_sup.erl"},{line,39}]},{supervisor,init,1,[{file,"supervisor.erl"},{line,294}]},{gen_server,init_it,2,[{file,"gen_server.erl"},{line,365}]},{gen_server,init_it,6,[{file,"gen_server.erl"},{line,333}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]},{wxr_app,start,[normal,[]]}} in application_master:init/4 line 134
2018-05-17 16:26:50.839 [error] <0.145.0> CRASH REPORT Process <0.145.0> with 0 neighbours exited with reason: {{{case_clause,undefined},[{wxr_sup,init,1,[{file,"src/wxr_sup.erl"},{line,39}]},{supervisor,init,1,[{file,"supervisor.erl"},{line,294}]},{gen_server,init_it,2,[{file,"gen_server.erl"},{line,365}]},{gen_server,init_it,6,[{file,"gen_server.erl"},{line,333}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]},{wxr_app,start,[normal,[]]}} in application_master:init/4 line 134
2018-05-17 16:27:29.011 [error] <0.147.0>@wxr_sup:init:39 CRASH REPORT Process <0.147.0> with 0 neighbours crashed with reason: no case clause matching undefined in wxr_sup:init/1 line 39
2018-05-17 16:27:29.057 [error] <0.147.0>@wxr_sup:init:39 CRASH REPORT Process <0.147.0> with 0 neighbours crashed with reason: no case clause matching undefined in wxr_sup:init/1 line 39
2018-05-17 16:27:29.071 [error] <0.147.0>@wxr_sup:init:39 CRASH REPORT Process <0.147.0> with 0 neighbours crashed with reason: no case clause matching undefined in wxr_sup:init/1 line 39
2018-05-17 16:27:29.012 [error] <0.145.0> CRASH REPORT Process <0.145.0> with 0 neighbours exited with reason: {{{case_clause,undefined},[{wxr_sup,init,1,[{file,"src/wxr_sup.erl"},{line,39}]},{supervisor,init,1,[{file,"supervisor.erl"},{line,294}]},{gen_server,init_it,2,[{file,"gen_server.erl"},{line,365}]},{gen_server,init_it,6,[{file,"gen_server.erl"},{line,333}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]},{wxr_app,start,[normal,[]]}} in application_master:init/4 line 134
2018-05-17 16:27:29.057 [error] <0.145.0> CRASH REPORT Process <0.145.0> with 0 neighbours exited with reason: {{{case_clause,undefined},[{wxr_sup,init,1,[{file,"src/wxr_sup.erl"},{line,39}]},{supervisor,init,1,[{file,"supervisor.erl"},{line,294}]},{gen_server,init_it,2,[{file,"gen_server.erl"},{line,365}]},{gen_server,init_it,6,[{file,"gen_server.erl"},{line,333}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]},{wxr_app,start,[normal,[]]}} in application_master:init/4 line 134
2018-05-17 16:27:29.071 [error] <0.145.0> CRASH REPORT Process <0.145.0> with 0 neighbours exited with reason: {{{case_clause,undefined},[{wxr_sup,init,1,[{file,"src/wxr_sup.erl"},{line,39}]},{supervisor,init,1,[{file,"supervisor.erl"},{line,294}]},{gen_server,init_it,2,[{file,"gen_server.erl"},{line,365}]},{gen_server,init_it,6,[{file,"gen_server.erl"},{line,333}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]},{wxr_app,start,[normal,[]]}} in application_master:init/4 line 134
2018-05-17 16:41:10.800 [error] <0.179.0>@gen_server:call CRASH REPORT Process <0.179.0> with 0 neighbours exited with reason: no such process or port in call to gen_server:call({global,public_data_srv}, {mfa,public_data_lib,get,[5,{0,1528041600}]}) in gen_server:call/2 line 206
2018-05-17 16:41:10.800 [error] <0.162.0>@gen_server:call Supervisor wxr_sup had child battle_master_srv started with battle_master_srv:start_link() at undefined exit with reason no such process or port in call to gen_server:call({global,public_data_srv}, {mfa,public_data_lib,get,[5,{0,1528041600}]}) in context start_error
2018-05-17 16:41:10.800 [error] <0.160.0> CRASH REPORT Process <0.160.0> with 0 neighbours exited with reason: {{shutdown,{failed_to_start_child,battle_master_srv,{noproc,{gen_server,call,[{global,public_data_srv},{mfa,public_data_lib,get,[5,{0,1528041600}]}]}}}},{wxr_app,start,[normal,[]]}} in application_master:init/4 line 134
2018-05-17 16:45:22.634 [error] <0.179.0>@gen_server:call CRASH REPORT Process <0.179.0> with 0 neighbours exited with reason: no such process or port in call to gen_server:call({global,public_data_srv}, {mfa,public_data_lib,get,[5,{0,1528041600}]}) in gen_server:call/2 line 206
2018-05-17 16:45:22.634 [error] <0.162.0>@gen_server:call Supervisor wxr_sup had child battle_master_srv started with battle_master_srv:start_link() at undefined exit with reason no such process or port in call to gen_server:call({global,public_data_srv}, {mfa,public_data_lib,get,[5,{0,1528041600}]}) in context start_error
2018-05-17 16:45:22.634 [error] <0.160.0> CRASH REPORT Process <0.160.0> with 0 neighbours exited with reason: {{shutdown,{failed_to_start_child,battle_master_srv,{noproc,{gen_server,call,[{global,public_data_srv},{mfa,public_data_lib,get,[5,{0,1528041600}]}]}}}},{wxr_app,start,[normal,[]]}} in application_master:init/4 line 134
2018-05-17 16:46:45.556 [error] <0.179.0>@gen_server:call CRASH REPORT Process <0.179.0> with 0 neighbours exited with reason: no such process or port in call to gen_server:call({global,public_data_srv}, {mfa,public_data_lib,get,[5,{0,1528041600}]}) in gen_server:call/2 line 206
2018-05-17 16:46:45.556 [error] <0.162.0>@gen_server:call Supervisor wxr_sup had child battle_master_srv started with battle_master_srv:start_link() at undefined exit with reason no such process or port in call to gen_server:call({global,public_data_srv}, {mfa,public_data_lib,get,[5,{0,1528041600}]}) in context start_error
2018-05-17 16:46:45.556 [error] <0.160.0> CRASH REPORT Process <0.160.0> with 0 neighbours exited with reason: {{shutdown,{failed_to_start_child,battle_master_srv,{noproc,{gen_server,call,[{global,public_data_srv},{mfa,public_data_lib,get,[5,{0,1528041600}]}]}}}},{wxr_app,start,[normal,[]]}} in application_master:init/4 line 134
2018-05-17 17:00:44.340 [error] <0.179.0>@gen_server:call CRASH REPORT Process <0.179.0> with 0 neighbours exited with reason: no such process or port in call to gen_server:call({global,public_data_srv}, {mfa,public_data_lib,get,[5,{0,1528041600}]}) in gen_server:call/2 line 206
2018-05-17 17:00:44.341 [error] <0.162.0>@gen_server:call Supervisor wxr_sup had child battle_master_srv started with battle_master_srv:start_link() at undefined exit with reason no such process or port in call to gen_server:call({global,public_data_srv}, {mfa,public_data_lib,get,[5,{0,1528041600}]}) in context start_error
2018-05-17 17:00:44.341 [error] <0.160.0> CRASH REPORT Process <0.160.0> with 0 neighbours exited with reason: {{shutdown,{failed_to_start_child,battle_master_srv,{noproc,{gen_server,call,[{global,public_data_srv},{mfa,public_data_lib,get,[5,{0,1528041600}]}]}}}},{wxr_app,start,[normal,[]]}} in application_master:init/4 line 134
2018-05-17 17:04:34.687 [error] <0.179.0>@gen_server:call CRASH REPORT Process <0.179.0> with 0 neighbours exited with reason: no such process or port in call to gen_server:call({global,public_data_srv}, {mfa,public_data_lib,get,[5,{0,1528041600}]}) in gen_server:call/2 line 206
2018-05-17 17:04:34.687 [error] <0.162.0>@gen_server:call Supervisor wxr_sup had child battle_master_srv started with battle_master_srv:start_link() at undefined exit with reason no such process or port in call to gen_server:call({global,public_data_srv}, {mfa,public_data_lib,get,[5,{0,1528041600}]}) in context start_error
2018-05-17 17:04:34.687 [error] <0.160.0> CRASH REPORT Process <0.160.0> with 0 neighbours exited with reason: {{shutdown,{failed_to_start_child,battle_master_srv,{noproc,{gen_server,call,[{global,public_data_srv},{mfa,public_data_lib,get,[5,{0,1528041600}]}]}}}},{wxr_app,start,[normal,[]]}} in application_master:init/4 line 134
2018-05-17 17:05:37.203 [error] <0.179.0>@gen_server:call CRASH REPORT Process <0.179.0> with 0 neighbours exited with reason: no such process or port in call to gen_server:call({global,public_data_srv}, {mfa,public_data_lib,get,[5,{0,1528041600}]}) in gen_server:call/2 line 206
2018-05-17 17:05:37.203 [error] <0.162.0>@gen_server:call Supervisor wxr_sup had child battle_master_srv started with battle_master_srv:start_link() at undefined exit with reason no such process or port in call to gen_server:call({global,public_data_srv}, {mfa,public_data_lib,get,[5,{0,1528041600}]}) in context start_error
2018-05-17 17:05:37.203 [error] <0.160.0> CRASH REPORT Process <0.160.0> with 0 neighbours exited with reason: {{shutdown,{failed_to_start_child,battle_master_srv,{noproc,{gen_server,call,[{global,public_data_srv},{mfa,public_data_lib,get,[5,{0,1528041600}]}]}}}},{wxr_app,start,[normal,[]]}} in application_master:init/4 line 134
2018-05-17 17:08:35.309 [error] <0.162.0>@gen_server:call Supervisor wxr_sup had child wxr started with wxr_srv:start_link(player) at undefined exit with reason no such process or port in call to gen_server:call({global,node_pool}, {attach,'player_8000_1@192.168.1.72'}) in context start_error
2018-05-17 17:08:35.309 [error] <0.163.0>@gen_server:call CRASH REPORT Process <0.163.0> with 0 neighbours exited with reason: no such process or port in call to gen_server:call({global,node_pool}, {attach,'player_8000_1@192.168.1.72'}) in gen_server:call/2 line 206
2018-05-17 17:08:35.309 [error] <0.160.0> CRASH REPORT Process <0.160.0> with 0 neighbours exited with reason: {{shutdown,{failed_to_start_child,wxr,{noproc,{gen_server,call,[{global,node_pool},{attach,'player_8000_1@192.168.1.72'}]}}}},{wxr_app,start,[normal,[]]}} in application_master:init/4 line 134
2018-05-17 17:51:42.548 [error] <0.182.0>@gen_server:call CRASH REPORT Process <0.182.0> with 0 neighbours exited with reason: no such process or port in call to gen_server:call({global,public_data_srv}, {mfa,public_data_lib,get,[5,{0,1528041600}]}) in gen_server:call/2 line 206
2018-05-17 17:51:42.549 [error] <0.162.0>@gen_server:call Supervisor wxr_sup had child battle_master_srv started with battle_master_srv:start_link() at undefined exit with reason no such process or port in call to gen_server:call({global,public_data_srv}, {mfa,public_data_lib,get,[5,{0,1528041600}]}) in context start_error
2018-05-17 17:51:42.549 [error] <0.160.0> CRASH REPORT Process <0.160.0> with 0 neighbours exited with reason: {{shutdown,{failed_to_start_child,battle_master_srv,{noproc,{gen_server,call,[{global,public_data_srv},{mfa,public_data_lib,get,[5,{0,1528041600}]}]}}}},{wxr_app,start,[normal,[]]}} in application_master:init/4 line 134
